### ISSUE TITLE
Feature request: Support Assets deletion by qualified name

### ISSUE THREAD

**Issue by archenroot** [atlanhq/atlan-java#394]
It would be handy if client.assets.delete() methods supports not only guids, but also qualified names.

**Comment by archenroot** [comment]
I am closing this as I think GUID is just fine to work with.

**Comment by cmgrote** [comment]
There isn't any direct API to call to delete something based on its `qualifiedName` — so at best the SDK would be hiding the fact that it would need to make multiple calls to do such a deletion (looking up the GUID by `qualifiedName`, and then doing the deletion by GUID).

Still perfectly feasible to do this yourself through the SDKs, just some extra steps — but we've left this so that it's clear multiple calls are being made so that the performance impact is obvious. You'd just need to combine these operations:

1. Search by `qualifiedName` (you can use a `terms` query to search by multiple `qualifiedName`s all in a single request): 
    - Search by `qualifiedName`: https://developer.atlan.com/search/attributes/common/#assetqualified_name
    - Terms query: https://developer.atlan.com/search/queries/terms/#terms
2. Delete by GUID (can batch up the results above to limit the delete calls): https://developer.atlan.com/snippets/advanced-examples/delete/#bulk-delete-assets
